const dummyData = {
    "data": {
        "headline": "DOCTOR FIMAN - A SPECIALIST AND A VERY FUNNY",
        "total_length": 155968,
        "topics": [
            {
                "start": 1705,
                "topic": "RICHARD FIMAN - A QUANTUM PHYSICS ART",
                "content": "RICHARD FIMAN WAS AN INCREDIBLE SCIENTIST HE SPENT MOST OF HIS TIME IN CALTA THE IDEA OF QUANTUM PHYSICS WERE ALL THESE PARTICLES IN WER ACTING IN MYSTERIOUS WAYS HE CAME UP WITH A THING CALLED FINEMEN DIAGRAMS THAT HE WON THE NOWEL PRIZE FOR PERHAPS EVEN MORE IMPORTANTLY HE WAS AN AMAZING TEACHER A SERIES OF LECTURES WHICH WERE FOR PEOPLE WHO DIDN'T SPECIALIZE IN PHYSICS IT'S SUCH A GREAT EXAMPLE OF HOW HE COULD EXPLAIN THINGS IN A FUN AND INTERESTING WAY TO ANY ONE AND HE'S VERY FUNNY INCIDENTALLY AT THE TIME OF HE KEPLER THE FARMER WAT"
            },
            {
                "start": 51710,
                "topic": "ANGELS - WINGS GON'T BE A WINNER ",
                "content": "AROND ORDER AS WE'LL SEE THAT THAT ANSWER IS NOT VERY FAR FROM THE TRUTH THE ONLY DIFFERENCE IS THAT THE ANGELS SIT IN A DIFFERENT DIRECTION AND WERE WINGS GON"
            },
            {
                "start": 63764,
                "topic": "DOCTOR FIMAN USED A DOCTOR FIMAN USED A ",
                "content": "DOCTOR FIMAN USED A"
            },
            {
                "start": 76109,
                "topic": "HE HAD PUSHED HIMSELF TO HAVE SUCH A DEEP",
                "content": "I REALLY UNDERSTAND THIS AND BECAUSE HE HAD PUSHED HIMSELF TO HAVE SUCH A DEEP UNDERSTAND HIS ABILITY TO TAKE YOU THROUGH THE PATH OF THE DIFFERENT POSSIBILITIES WAS INCREDIBLE"
            },
            {
                "start": 92180,
                "topic": "GET IT FASTER BY HEATING IT UP SOMEHOW SOME",
                "content": "CAN GET IT FASTER BY HEATING IT UP SOMEHOW SOMEWAY THEY COME CLOSE ENOUGH TO THE CARBON AND SNAP IN AND THAT GIVES A LOT OF JIGGLYMO WHICH MIGHT HIT SOME OTHER ATOMS MAKING THOSE GO FASTER SO THEY CAN CLIMB UP AND BUMP AGAINST OTHER CARBON ATOMS AND THEY GIGGLE AND THEY MAKE MOTHERS GIGGLE AND YOU GET A TERRIBLE CATAST"
            },
            {
                "start": 119306,
                "topic": "FINMAN MADE SCIENCE SO FASCINATING HE DOESN'T",
                "content": "TO EXPLAIN HOW IT WORKS HE DOESN'T EVEN TELL YOU HE'S TALKING ABOUT FIRE TILL THE VERY END AND YOU FEEL LIKE YOU'R KIND OF FIGURING IT OUT TOGETHER WITH HIM FINMAN MADE SCIENCE SO FASCINATING HE REMINDS US HOW MUCH FUN IT IS AND EVERYBODY CAN HAVE A PRETTY FULL UNDERSTANDING SO HE'S SUCH A JOYFUL EXAMPLE OF HOW ALL LIKE TO TO LEARN AND THINK ABOUT THINGS"
            }
        ]
    }
}

export default dummyData;